---
#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: true

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module

###########
# Plugins #
###########
plugins:
  - '@typescript-eslint'

##############################
# Extend to disable Prettier #
# and JS-Standard linters    #
##############################
extends: 
  - prettier 
  - standard
  
#########
# Rules #
#########
rules:
  quotes:
  - warning
  - double
  semi:
  - warning
  lines-around-comment:
  - error
  - beforeBlockComment: true
    afterBlockComment: true
    beforeLineComment: true
    afterLineComment: true
    allowBlockStart: true
    allowBlockEnd: true
    allowObjectStart: true
    allowObjectEnd: true
    allowArrayStart: true
    allowArrayEnd: true
    

##############################
# Overrides for JSON parsing #
##############################
overrides:

  # JSON files
  - files:
      - "*.json"
    extends:
      - plugin:jsonc/recommended-with-json
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON

  # JSONC files
  - files:
      - "*.jsonc"
    extends:
      - plugin:jsonc/recommended-with-jsonc
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSONC

  # JSON5 files
  - files:
      - "*.json5"
    extends:
      - plugin:jsonc/recommended-with-json5
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON5
